# Generated by Django 4.0.5 on 2022-06-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='fecha de la extension', verbose_name='fecha')),
                ('fechaFinPrevista', models.DateField(help_text='fecha fin prevista', verbose_name='fechaFinPrevista')),
                ('motivo', models.CharField(help_text='motivo de la extension', max_length=200, verbose_name='motivo')),
            ],
            options={
                'verbose_name': 'extension mantenimiento',
                'verbose_name_plural': 'extensiones mantenimiento',
                'ordering': ['fecha', 'fechaFinPrevista', 'motivo'],
            },
        ),
    ]
